### ISSUE TITLE
No data viewer

### ISSUE THREAD

**Issue by babibabo** [Microsoft/RTVS#2053]
Hello, 

When I want see my data clicking in the Variable Explorer or with "View(data)", nothing is shown (like in the image).

![image](https://cloud.githubusercontent.com/assets/20184321/16647815/4a4223d4-4431-11e6-9857-6b3159bf1eca.png)

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.10586.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.4.20623.1711, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\Microsoft\R Client\R_SERVER\

**Comment by MikhailArkhipov** [comment]
Does it help if you reset REPL window?

**Comment by babibabo** [comment]
Thank you for your help, but I do not see what is REPL windows ? How can I do to reset it ?
I have this problem each time, even when I close then open RTVS again.

**Comment by MikhailArkhipov** [comment]
REPL is R Interactive window (read-eval-print loop). there is an icon on its toolbar for resetting.

**Comment by babibabo** [comment]
I did not know it are called like this, thanks. So, all work with 3 data.frame, but with the 4th I get this :
(the steps are in yellow)
![capture](https://cloud.githubusercontent.com/assets/20184321/16692132/b8bb0322-452f-11e6-9d3f-aeb7937817b4.PNG)

**Comment by babibabo** [comment]
The problem happens when I try to view it before or after to have been opened others data.frames. 

It is specific to it and some others else (they are a minority). I do not know what is the specific problem. With a str(), it tells us that they are basic data.frames (with factors, integers, dates and characters) and they are smaller than others data.frames which are correctly shown.

(sorry for my english, I hope it is comprehensive)

**Comment by int19h** [comment]
Would it be possible for you to share the code that produces one of those non-working dataframes?

**Comment by babibabo** [comment]
Here you can find my code for the exemple of the "parametre" dataframe in the picture above. It is just a simple imported CSV with some modifications.
```
parametre <- read.csv(paste(Chemin, "parametres_mars.csv", sep = ""), header = FALSE, sep = ";", quote = "\"")
names(parametre) <- c("FLD_ACCES_ID", "FLD_PORTE", "FLD_TYPE_RECHARGE", "FLD_NB_J_DEB", "FLD_CD_OFFRE", "FLD_IS_FORFAIT", "FLD_NB_RECH_MOIS", "XXX", "FLD_DEP_MAG_SOUS", "FLD_DATE_ACT", "FLD_DATE_RESI", "FLD_SMARTPHONE")
parametre[parametre == "\\N"] <- NA
parametre$FLD_DATE_ACT <- as.Date(parametre$FLD_DATE_ACT, "%Y-%m-%d")
parametre$FLD_DATE_RESI <- as.Date(parametre$FLD_DATE_RESI, "%Y-%m-%d")
parametre$resiliation = "NON"
parametre[ parametre$FLD_DATE_RESI < as.Date("2016-04-01"), "resiliation" ] <- "OUI"
```

**Comment by int19h** [comment]
Could you share parametres_mars.csv? Or, alternatively, an Rdata file from the session where this is loaded. It would be easiest to debug if I could reproduce it locally.

**Comment by babibabo** [comment]
Sure, this is the Rdata file of "parametre" : [parametre.zip](https://github.com/Microsoft/RTVS/files/360912/parametre.zip)

**Comment by chenweichen** [comment]
Dear MikhailArkhipov/ int19h,
I got the same problem.

**R Information:**
R Install path:
D:\R\R-3.3.1

R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Chinese (Traditional)_Taiwan.950  LC_CTYPE=Chinese (Traditional)_Taiwan.950   
[3] LC_MONETARY=Chinese (Traditional)_Taiwan.950 LC_NUMERIC=C                                
[5] LC_TIME=Chinese (Traditional)_Taiwan.950    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] rtvs_1.0.0.0

**Visual Studio & RTVS Information:**
Microsoft Visual Studio Community 2015
Version 14.0.25421.03 Update 3
Microsoft .NET Framework
Version 4.6.01038
Installed Version: Community
R Tools for Visual Studio   0.4.20623.1711

**My code:**
y<-mtcars
z<-iris
You can see my result via the link ( http://imgur.com/a/pc7gV )
R Data:z and R Data:y are empty.

**Comment by rminder** [comment]
I installed .4.20623.1711 yesterday, in Visual Studio Community, issued a query against a SQL database and clicked the Show Item Details button next to my data set in the Variable Explorer and got nothing but a blank page.

**Comment by int19h** [comment]
@rminder, what's your locale?

**Comment by int19h** [comment]
@babibabo, @chenweichen, @rminder: can you do R Tools | Feedback | Send Frown, and attach the logs, if possible (i.e. if there's no private information in them)?

**Comment by rminder** [comment]
Ohio

**Comment by int19h** [comment]
Sorry, I meant R locale. As in, what does `Sys.getlocale()` return for you?

**Comment by rminder** [comment]
I wondered why you asked me that, but I assumed you might push different
bits to different folks around the world.


"LC_COLLATE=English_United States.1252;LC_CTYPE=English_United
States.437;LC_MONETARY=English_United
States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"

**Comment by babibabo** [comment]
This is mine :

`"LC_COLLATE=French_France.1252;LC_CTYPE=French_France.850;LC_MONETARY=French_France.1252;LC_NUMERIC=C;LC_TIME=French_France.1252"`

**Comment by chenweichen** [comment]
Dear @int19h
May I send my logs to your email box(int19h@gmail.com)?

**Comment by int19h** [comment]
Please send them to rtvsuserfeedback@microsoft.com.

**Comment by rminder** [comment]
Please send what?

**Comment by int19h** [comment]
I was responding to the preceding comment on this issue (you're getting emails for every new comment here, because you're subscribed to the issue).

**Comment by chenweichen** [comment]
@int19h 
I sent you my RTVS logs a few minutes age.
Please check your email box.
Thank you.

**Comment by huguesv** [comment]
Fixed for the next release. Sorry for the delay, and thanks for the repro!

If you would like to apply the fix to RTVS 0.4:

Replace the contents of grid.R with the latest version: https://github.com/Microsoft/RTVS/blob/master/src/Host/Client/Impl/rtvs/R/grid.R

You can find grid.R on your machine at the following location:
`C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\R Tools for Visual Studio\rtvs\R`

**Comment by chenweichen** [comment]
Dear @int19h   @huguesv 
Is this a bug that a dataset includes NA values?
I opened "mtcars" dataset via Excel, and then I found that there are no NA values.

My data table viewer tab still shows nothing even though I replaced  the contents of grid.R with the latest version.

I am very sorry to trouble again.

**Comment by huguesv** [comment]
Yes, the issue was with datasets with NA values.  I'm able to open "iris" and "mtcars" in data table viewer with the latest build.  They don't look like they have NA values, so this may be a different issue, or an issue that was fixed somewhere else prior to my change in grid.R.  I'll setup a Chinese traditional windows machine and try it out.

**Comment by rminder** [comment]
Any idea when the next version is coming out? It's been since June, I
think, that we've seen an update. I'm beginning to think Microsoft has
abandonend this project, and I should go back to using RStudio.

Randy

**Comment by MikhailArkhipov** [comment]
Soon :-) Out plans are actually public here on GitHub. You can see active commits etc. If you install ZenHub extension to Chrome you should also see Epics, milestones and the burndown chart.

**Comment by int19h** [comment]
You can keep an eye on what's going on here:

https://github.com/Microsoft/RTVS/graphs/

and specific commits here:

https://github.com/Microsoft/RTVS/commits/master

We develop directly in this repo, so you can observe the functionality as it goes in. Hopefully the activity data since June is convincing proof that nothing's being abandoned. :)

If you'd like to check out the intermediate product, we don't have any kind of public automated daily build system (yet), but it's fairly easy to build from source. Just keep in mind that we're in active feature development stage right now, so new code comes in hot, and the bits in master are neither complete nor stable.

**Comment by rminder** [comment]
Yes, thank you, I do see activity since June. But nothing like the activity
that occurred from August last year to June of this year and it looks like
the main developer, Mikhail has done very little since the end of July
(except issue pull requests). It appears only three people are actively
working on this. I'm sure this isn't a particularly high priority at
Microsoft.

**Comment by MikhailArkhipov** [comment]
You know, people do take vacations occasionally :-) It always has been ~4 people. Amount of submits naturally goes down as product matures. In fact, it would be alarming of volume of changes would be same as year ago when new code was being created. High churn usually means code was bad or wrong and has to be changed a lot.

**Comment by rminder** [comment]
Fair enough. I think RTVS could be an exciting product and I'm looking
forward to the next update.

**Comment by MikhailArkhipov** [comment]
We are also working on release and more code going forward. For example, RTVS will be able to use R installed on remote machine. Although the feature does not involve a lot of raw code changes (as in number of lines), the changes are deep and complex so it takes time. Upcoming integration with SQL tools also does not constitute a lot of code lines, but it required a lot of research and [invisible here] work with SQL Tools team.

**Comment by MikhailArkhipov** [comment]
Add support for VS 15 Preview to this. Very little code changes, quite a bit of testing and internal release preparations. RTVS will come in box with VS 15 Preview (aka VS 2017).

**Comment by smortaz** [comment]
The real reason for the apparent lack of activity is:

1. vacation period
2. two major features being worked on: SQL integration;  Remoting;

V0.5 should be out in a few weeks.



On Mon, Sep 19, 2016 at 12:17 PM, Mikhail Arkhipov <notifications@github.com

**Comment by ZeroFung** [comment]
I am new to RTVS and I have the same problem. Nothing show when i View(mtcars).

Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA004
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA004
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA004
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

R Tools for Visual Studio   0.5.21008.0800
Provides project system, R Interactive window, plotting, and more for the R programming language.

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

**Comment by MikhailArkhipov** [comment]
Try 0.5 at https://aka.ms/rtvs-current

**Comment by ZeroFung** [comment]
@MikhailArkhipov Sorry but my RTVS is 0.5. Still don`t work. View(mtcars) and i get a blank page.

**Comment by MikhailArkhipov** [comment]
@huguesv , I thought it was https://github.com/Microsoft/RTVS/issues/2154 ?
