### ISSUE TITLE
Data Viewer returns blank window

### ISSUE THREAD

**Issue by mugofjoe** [Microsoft/RTVS#2561]
Specs: 
Windows 10 Enterprise v 10.0.10586 Build 10586
Visual Studio Professional 2015 v 14.0.25431.01 Update 3
R Tools for Visual Studio 0.4.20623.1711

Hello,

I noticed that invoking the View( ) function on a data set brings up a tabbed window in Visual Studio but it comes up blank.   

![j1](https://cloud.githubusercontent.com/assets/14941750/19686798/cd9341ea-9a90-11e6-8d76-9af9ea5b59e7.png)

The interesting is when I try to switch to an open .Rmd file and execute Set Working Directory to Source File Location (Ctrl+Shift+E) and then switch back to the data viewer window, the data now appears.

![j2](https://cloud.githubusercontent.com/assets/14941750/19686829/f84b5d28-9a90-11e6-9446-5466b29807e1.png)

Here's my R version information

![j3](https://cloud.githubusercontent.com/assets/14941750/19686907/5c0e8a92-9a91-11e6-8f2e-1ac13e365c16.png)

Thanks!
Joel
manilamocha@gmail.com

**Comment by mugofjoe** [comment]
BTW, I missed mentioning that I have turned off all my extensions in Visual Studio before executing the View function. 

The same behavior happens when I just click on the Show Item Details icon (magnifying glass) in the Variable Explorer pane.

**Comment by huguesv** [comment]
Thanks for the report.

We've fixed some issues with NULL values in variable explorer in RTVS 0.5 (download from here: http://microsoft.github.io/RTVS-docs/). I'm pretty sure that's not the issue here but I would recommend upgrading anyway.

If instead of changing the current directory, you just run `1+1` in the R interactive window, does that make the data appear too?

We've had other users report a similar issue, but haven't been able to reproduce it here yet.

**Comment by mugofjoe** [comment]
Hi Hugues,

Thanks for the quick reply. Just installed 0.5 (cool new stuff!) and tried the `View( )` function again but we still have the same problem.   I also tried `1+1` , still no data.

I played around a bit and, I don't know the innards of VS, but the troubleshooting part of me thought that perhaps it might have something to do with the _refreshing_  mechanism of the data window (e.g. the way the window first tries to display itself).

To test this, I issued the `View(cars)` function from the interactive console afresh.... the blank window shows up.  Then, I right-clicked on the tab of the (blank) data window itself and clicked on Hide. 

So, the window was gone (as expected).

I switched back to the interactive console and typed in the `View(cars)` statement again and voila! the data appeared!

So, I think that perhaps it may have something to do with some window refreshing mechanism or whatnot.  I hope that makes sense.

I have enclosed the _Copy Info_ information that VS provides inside its Help | About modal window in case that might help.

![2561_01](https://cloud.githubusercontent.com/assets/14941750/19697253/aa0b4a6a-9ab8-11e6-9fa2-f7c85b235864.png)



[Issue 2561 Copy Info.txt](https://github.com/Microsoft/RTVS/files/551348/Issue.2561.Copy.Info.txt)

**Comment by MikhailArkhipov** [comment]
Can you please send us frown via R Tools | Feedback. It will include app logs. Thanks.

**Comment by mugofjoe** [comment]
Hi Mikhail,
Thank you for assisting me on this. I just sent you an email about the R Tools Feedback you requested along with the RTVSLogs compressed file that it generated.

Look for the email entitled:
Data Viewer returns blank window #2561

Thanks, --  Joel

**Comment by mugofjoe** [comment]
Hi Mikhail,
Let me know if there's anything else you need from me. Thanks.

**Comment by int19h** [comment]
The logs don't offer any clues, unfortunately - everything there is as it should be. As soon as `View(cars)` was issued, we started fetching data, and the results look correct; certainly nothing to explain the blank window.

Unfortunately, I couldn't repro it on current builds, either, so I can't do live debugging.

One thing that I would suggest is resetting VS, and seeing what exact steps you need to do, starting from VS launch, to get to that blank window (e.g. which tool windows you're activating, if any, etc). There may be some clues there.

Of course, it's possible that we have just inadvertently fixed it altogether - if it's really related to UI refresh not being triggered properly, which seems likely, that would be affected by the many fixes that we've done around R session lifecycle in the past couple of months (and which aren't, for the most part, in 0.5).

**Comment by mugofjoe** [comment]
Thank you. I'll check this again and try to reset VS.

**Comment by gsmoon** [comment]
I have also encountered this problem with my two computers. Do you solve it now?

**Comment by mugofjoe** [comment]
No, I'm still experiencing it in Visual Studio. I've been using RStudio in the meantime until perhaps it gets fixed in the next update or release.  It's quite a downer since it would have been great not to go out of Visual Studio to do my R work. But the problem can't seem to be replicated on the developers' end.

Don't get me wrong, the developers have been more than responsive and very prompt at their replies. And I thank them a lot. It's just that it's difficult to solve a bug if it can't be replicated. :-/

**Comment by smortaz** [comment]
@pavel can we send them a current build to see whether this issue is fixed
or still reproduces?

**Comment by fengyanhao** [comment]
@mugofjoe I also have the same problem with you. So have you fixed this problem? If you had, how to do it? Thank you very much!

**Comment by mugofjoe** [comment]
hey @fengyanhao 

Unfortunately, the problem persists. I've enclosed a screenshot of my VS install info:

![ms-rtooslversion](https://cloud.githubusercontent.com/assets/14941750/21391553/32bc3716-c75a-11e6-8920-b6366f9ec76f.png)


Here's what I get when I execute a `View(mtcars)` command:

![image](https://cloud.githubusercontent.com/assets/14941750/21391734/eaef1c72-c75a-11e6-919c-55e857ebacf2.png)

**Comment by mugofjoe** [comment]
@gsmoon  @fengyanhao  

I just noticed something. When I dragged the R Interactive panel (usually at the bottom of my IDE but it may be in a different location on your end based on how you configured your VS working environment) and let it snap to the main portion of the screen so that it sits side-by-side with the Data Viewer panel, the Data Viewer panel which was previously blank, flickers a bit and then suddenly shows the data. 

I think I mentioned somewhere along my previous threads that it might have something to do with the way Visual Studio refreshes the screen whenever there's an activity.  I do believe that the data for the Data Viewer has always been there the first time one executes the `View( )` function but graphic elements come up somewhat hidden.   A change in the VS environment triggers the graphics or data table to show itself.  

Hopefully, this might give a clue to our developers... 

Can you try the same and see if that also happens on your end?



![image](https://cloud.githubusercontent.com/assets/14941750/21391839/50ab87c6-c75b-11e6-934c-effe2390c52f.png)

**Comment by MikhailArkhipov** [comment]
Out of curiosity, what kind of video driver/controller the machine has? You can determine this by Start -> type 'DxDiag'

**Comment by MikhailArkhipov** [comment]
I think I found the problem

**Comment by MikhailArkhipov** [comment]
Added to PR https://github.com/Microsoft/RTVS/pull/2935

**Comment by mugofjoe** [comment]
![image](https://cloud.githubusercontent.com/assets/14941750/21529912/da12f7e2-cd0a-11e6-9312-6c54643f275d.png)

**Comment by mugofjoe** [comment]
@MikhailArkhipov where you able to replicate the problem on your end?

**Comment by MikhailArkhipov** [comment]
No, but I found piece of code that might be skipping setting evaluated data on the grid under certain conditions. Then when window resizes it refreshes the view and the data appears. We will be releasing 0.6 very soon so you should be able to verify.

**Comment by MikhailArkhipov** [comment]
Closing for now with https://github.com/Microsoft/RTVS/commit/fecbdbb4621d16e0727ffd3b2928503fde73c78e. If reproes in upcoming 0.6, will reactivate.

**Comment by fengyanhao** [comment]
@mugofjoe Sorry to answer such late. I have tried to drag windows and still get nothing. I have noticed that developers have already noticed this problem. Looking forward to next version. And thank you very much.

**Comment by GreenEric** [comment]
well, it happens to me as well. I am pretty sure i installed the latest version of VS, RTVS and MRO.
many thanks.
![baidushurufa_2017-2-8_16-18-1](https://cloud.githubusercontent.com/assets/24875340/22731820/f30a7062-ee26-11e6-8fdb-7ce8832e89d5.png)

**Comment by mugofjoe** [comment]
I have just installed R Tools for Visual Studio 1.0.30225.1011 RC2. This is still an issue. 
I executed a View(mtcars) function and it returned a blank data viewer panel.


![image](https://cloud.githubusercontent.com/assets/14941750/23464041/9a4c1c0a-fe61-11e6-86ce-05c489e0b0ba.png)
