### ISSUE TITLE
Function arguments in tooltips messed up

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3095]
... when you have multiple functions listed in a single help file.

![image](https://cloud.githubusercontent.com/assets/11328890/22545270/200dbee2-e98c-11e6-8c82-35aa601c91c4.png)

This is because `?parLapply` (in the parallel package) shares the same help page as a bunch of related functions:

```
clusterCall(cl = NULL, fun, ...)
clusterApply(cl = NULL, x, fun, ...)
clusterApplyLB(cl = NULL, x, fun, ...)
clusterEvalQ(cl = NULL, expr)
clusterExport(cl = NULL, varlist, envir = .GlobalEnv)
clusterMap(cl = NULL, fun, ..., MoreArgs = NULL, RECYCLE = TRUE,
           SIMPLIFY = FALSE, USE.NAMES = TRUE,
           .scheduling = c("static", "dynamic"))
clusterSplit(cl = NULL, seq)

parLapply(cl = NULL, X, fun, ...)
parSapply(cl = NULL, X, FUN, ..., simplify = TRUE,
          USE.NAMES = TRUE)
parApply(cl = NULL, X, MARGIN, FUN, ...)
parRapply(cl = NULL, x, FUN, ...)
parCapply(cl = NULL, x, FUN, ...)

parLapplyLB(cl = NULL, X, fun, ...)
parSapplyLB(cl = NULL, X, FUN, ..., simplify = TRUE,
            USE.NAMES = TRUE)
```

**Comment by Hong-Revo** [comment]
I just noticed from the screenshot: should also tidy up handling of URLs in tooltips.

**Comment by MikhailArkhipov** [comment]
We don't currently show overrides list like C# does. Also, we use standard tooltip (i.e. we provide a string and that's it). It is possible to use custom WPF control with clickable links, eventually we'll provide that - see #1400

**Comment by Hong-Revo** [comment]
You'll have to explain it to me like I'm a total C# and VS noob (which I am ;) ). What's an override list?

**Comment by MikhailArkhipov** [comment]
So this appear to be effect of #1060 which has been there since at least 0.3. Apparently some documentation provides complete list of arguments in one of the signatures and incomplete in others. Also, most detailed list propagates to aliases

`parLapplyLB` ans `parSapply` are both listed as alias or `clusterApply`.

If this is incorrect, it is easy to revert #1060 and completion with then just show exactly what it is RD.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/a5c501548e392c0352a850cd2ddcd00f3f4968dd

**Comment by Hong-Revo** [comment]
This still appears to be an issue in 1.0RC1?

**Comment by MikhailArkhipov** [comment]
Yes. It was fixed for RC2.

**Comment by Hong-Revo** [comment]
I noticed that some functions are still incorrectly handled:

![image](https://cloud.githubusercontent.com/assets/11328890/26330305/9c457f4c-3f8e-11e7-8b7b-dd8a6bf732ef.png)

Actual signatures:

![image](https://cloud.githubusercontent.com/assets/11328890/26330316/aaa7dc92-3f8e-11e7-8607-b31119d7d90f.png)
