### ISSUE TITLE
R in Data Science Workload blocked from installing on Windows 7

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#3561]
Customers have reported that R in the VS 2017 Data Science Workload is blocked from installing on Windows 7. We have verified this issue and have a fix prepared for the next update of Visual Studio 2017. 

We are currently working with the Visual Studio team to get this fix deployed as quickly as possible.

**Comment by MikhailArkhipov** [comment]
Fixed, pending insertion in 15.2.2

**Comment by javierglozano** [comment]
Documentation page at https://docs.microsoft.com/en-us/visualstudio/rtvs/installation#installing-rtvs-in-visual-studio-2017 still shows a warning message about this issue...

**Comment by kraigb** [comment]
I verified that the right options show up with build 26430.12 on Windows 7. https://github.com/Microsoft/vsdocs/pull/502 is in to update the docs.
